// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tebox} from '../models';
import {main} from '../models';

export function ConfigureInstance(arg1:string,arg2:tebox.DeviceProfile):Promise<void>;

export function CreateInstance():Promise<tebox.Instance>;

export function DeleteInstance(arg1:string):Promise<void>;

export function GetStatus():Promise<main.Status>;

export function ListInstances():Promise<Array<tebox.Instance>>;

export function PowerDown(arg1:string):Promise<void>;

export function SendKey(arg1:string,arg2:string):Promise<void>;

export function StartInstance(arg1:string):Promise<void>;

export function StopInstance(arg1:string):Promise<void>;
