// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigureInstance(arg1, arg2) {
  return window['go']['main']['App']['ConfigureInstance'](arg1, arg2);
}

export function CreateInstance() {
  return window['go']['main']['App']['CreateInstance']();
}

export function DeleteInstance(arg1) {
  return window['go']['main']['App']['DeleteInstance'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ListInstances() {
  return window['go']['main']['App']['ListInstances']();
}

export function PowerDown(arg1) {
  return window['go']['main']['App']['PowerDown'](arg1);
}

export function SendKey(arg1, arg2) {
  return window['go']['main']['App']['SendKey'](arg1, arg2);
}

export function StartInstance(arg1) {
  return window['go']['main']['App']['StartInstance'](arg1);
}

export function StopInstance(arg1) {
  return window['go']['main']['App']['StopInstance'](arg1);
}
